### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NaturesProphet** [devfviak/node-hls-server#1]
how can i get a RTMP live stream and stream it to another clients with hls ?

**Comment by pedrio-gh** [comment]
Hi @NaturesProphet , have you tried adding the source RTMP live stream to your server like this? 

`server.addStream('rtmpToHlsName', 'rtmp://example/live/stream')
`
Where _server_ is an isntance of HLSServer.

If I understand your problem is that you have a RTMP stream and want to use this library to converte that RTMP stream to HLS, to do it, the above code should be correct. FFMPEG will encode your RTMP stream to HLS stream with the configuration you provide to HLSServer. 

In case you are doing what I commented please send me an example RTMP stream to make some tests and see what is going wrong.

Maybe you mean to generate both an RTMP and HLS live streams? Currently only encode to HLS (from any source accepted by FFMPEG)  is available.

Thank you, and don't hesitate to contact me.
